name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [main]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: CheckOut The Repo
                uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17
                    architecture: x64
            -   name: Cache Maven packages
                uses: actions/cache@v4.0.0
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2-
            - name: Build with Maven
              run: mvn --no-transfer-progress verify
            - name: Run Synopsys Detect
              uses: synopsys-sig/detect-action@v0.3.0
              with:
                  github-token: ${{ secrets.TOKEN_GITHUB }}
                  detect-version: 9.0.0
                  blackduck-url: ${{ secrets.BLACKDUCK_URL }}
                  blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
