name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [main]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: CheckOut The Repo
                uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17
                    architecture: x64
        
#            - name: Black Duck Intelligent Scan
#              uses: synopsys-sig/detect-action@v0.3.4
#              env:
#                  detect_blackduck_rapid_compare_mode: BOM_COMPARE_STRICT
#                  detect_tools: DETECTOR    
#              with:
#                  scan-mode: INTELLIGENT 
#                  github-token: ${{ secrets.GITHUB_TOKEN }}
#                  detect-version: 9.0.0
#                  blackduck-url: ${{ secrets.BLACKDUCK_URL }}
#                  blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}

            - name: Black Duck RAPID Scan
              uses: synopsys-sig/detect-action@v0.3.4
              env:
                  detect_blackduck_rapid_compare_mode: BOM_COMPARE_STRICT
              with:
                  scan-mode: STATELESS
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  detect-version: 9.0.0
                  blackduck-url: ${{ secrets.BLACKDUCK_URL }}
                  blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
